### ISSUE TITLE
Example didn't work for me. I changed it.

### ISSUE THREAD

**Issue by BirgitPohl** [Keats/gulp-example#1]
Heyho.

I just like you to know that your example unfortunately didn't work for me. I read your tutorial with great excitement and tried it out.

My problem was, that your example didn't change my destination file at all.
I myself wrote something that changed the destination only one time, once a change event triggered. But nothing after that happened.

So I am pretty happy to find this simple solution.
I understand why you want to use runSequence, but this one actually didn't do anything. So I left it out at called the actual function that writes the destination file.

Here are my changes that made a multiple synchronization work for me

``` coffee
gulp.watch './YourPath/**, (file) ->
    browserSync.reload(file.path) if file.type is "changed"
    gulp.start 'src'

#gulp.task 'build', ->
#  runSequence 'clean', ['src']
```

Btw, I like the clean style. Thanks for the tutorial.

**Comment by Keats** [comment]
Thanks!

This repo is actually very old (which is probably it doesn't work anymore), I will add on the README that it should be not really be used as an example anymore. For example, I wouldn't recommend using coffeescript.

A more recent example (still a few months old) of what I'm currently using would be https://github.com/Keats/flow-typescript/tree/master/typescript for example.
In short, webpack for typescript and modules and gulp mostly for sass/images/etc

Note that I use gulp4 in the repo above which is still in beta
